# Generated by Django 4.0.1 on 2022-02-12 22:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Metadata',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=64, unique=True, verbose_name='Table Name')),
                ('label', models.CharField(max_length=128, verbose_name='Label')),
                ('plural', models.CharField(max_length=128, verbose_name='Plural Label')),
                ('storage_app_label', models.CharField(max_length=64, verbose_name='Database Table Name')),
                ('storage_model', models.CharField(max_length=64, verbose_name='Database Table Name')),
                ('schema', models.JSONField(default=dict, verbose_name='Schema Data')),
                ('db_fields', models.JSONField(blank=True, default=dict, verbose_name='Database Fields')),
                ('field_map', models.JSONField(blank=True, default=dict, verbose_name='Field Map')),
                ('created', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Created')),
                ('modified', models.DateTimeField(auto_now=True, verbose_name='Modified')),
            ],
        ),
        migrations.CreateModel(
            name='MetadataVersion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=128, verbose_name='Label')),
                ('plural', models.CharField(max_length=128, verbose_name='Plural Label')),
                ('storage_app_label', models.CharField(max_length=64, verbose_name='Database Table Name')),
                ('storage_model', models.CharField(max_length=64, verbose_name='Database Table Name')),
                ('schema', models.JSONField(default=dict, verbose_name='Schema Data')),
                ('db_fields', models.JSONField(blank=True, default=dict, verbose_name='Database Fields')),
                ('field_map', models.JSONField(blank=True, default=dict, verbose_name='Field Map')),
                ('created', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Created')),
                ('modified', models.DateTimeField(auto_now=True, verbose_name='Modified')),
                ('name', models.CharField(db_index=True, max_length=64, verbose_name='Table Name')),
                ('metadata', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='custom_table.metadata')),
            ],
            options={
                'abstract': False,
                'index_together': {('storage_app_label', 'storage_model')},
            },
        ),
    ]
